all: true pause echo mkdir

true: true.c
	diet gcc -o true true.c
	strip -x true

pause: pause.c
	diet gcc -o pause pause.c
	strip -x pause

echo: echo.c
	diet gcc -o echo echo.c
	strip -x echo

mkdir: mkdir.c
	diet gcc -o mkdir mkdir.c
	strip -x mkdir
